### ISSUE TITLE
Scienti affiliations

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#106]
```.py
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi_log
  log_collection: log
workflow:
  scienti_affiliations:
    databases:
      - database_url: localhost:27017
        database_name: scienti_udea_2023
        collection_name: product
    verbose: 2
```

```.py
Loading plugin: kahi_scienti_affiliations
Running plugin: kahi_scienti_affiliations
Processing scienti_udea_2023 database
Plugin scienti_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 232, in run
    self.process_scienti_institutions(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 46, in process_scienti_institutions
    for inst in reg_scienti["group"][0]["institution"]:
                ~~~~~~~~~~~^^^^^^^^^
KeyError: 'group'
```

python 3.11

you can get db scienti_udea_2023 from our server in the cloud

**Comment by fedevergara** [comment]
Now the scienti_affiliations plugin successfully completes the processing of the scienti_udea_2023 data.
