### ISSUE TITLE
dates in scienti affiliations

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#107]
there is a problems in dates with some dbs such as
scienti_univalle_2023 and scienti_uec_2023

this two databases has different date from respect to scienti_udea_2023 and scienti_ual_2023

we need to check the format and parse the right date.

```.py
ozapatam@tuxito:~/data/kahi_data/kahi_data$ kahi_run --workflow configs/Kahi_scienti_affiliations.yml --verbose 5
OrderedDict([('config', OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'kahi'), ('log_database', 'kahi_log'), ('log_collection', 'log')])), ('workflow', OrderedDict([('scienti_affiliations', OrderedDict([('databases', [OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'scienti_univalle_2023'), ('collection_name', 'product')])]), ('verbose', 2)]))]))])
Log retrieved from database
[{'_id': 'scienti_affiliations', 'time': 1700761398, 'status': 1, 'message': "time data '2022-05-24 00:00:00' does not match format '%d %b %Y %H:%M:%S'", 'time_elapsed': 0}]
Loading plugin: kahi_scienti_affiliations
Running plugin: kahi_scienti_affiliations
Processing scienti_univalle_2023 database
Plugin scienti_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 233, in run
    self.process_scienti_groups(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 199, in process_scienti_groups
    "from_date": int(dt.strptime(group["DTA_CLASIF"].split(", ")[-1].replace(" GMT", ""), "%d %b %Y %H:%M:%S").timestamp()),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-05-24 00:00:00' does not match format '%d %b %Y %H:%M:%S'
``` 
 
example config
```.yml
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi_log
  log_collection: log
workflow:
  scienti_affiliations:
    databases:
      - database_url: localhost:27017
        database_name: scienti_univalle_2023
        collection_name: product
    verbose: 2

```

you can find all those databases in our cloud

**Comment by fedevergara** [comment]
The issue was solved by adding a function to check the format of some dates.
