### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#108]
config

```.py
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi_log
  log_collection: log
workflow:
  scienti_person:
    databases:
      - database_url: localhost:27017
        database_name: scienti_uec_2023
        collection_name: product
    verbose: 2
```

```.py
ozapatam@tuxito:~/data/kahi_data/kahi_data$ kahi_run --workflow configs/Kahi_scienti_person.yml --verbose 5
OrderedDict([('config', OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'kahi'), ('log_database', 'kahi_log'), ('log_collection', 'log')])), ('workflow', OrderedDict([('scienti_person', OrderedDict([('databases', [OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'scienti_uec_2023'), ('collection_name', 'product')])]), ('verbose', 2)]))]))])
Log retrieved from database
[{'_id': 'scienti_affiliations', 'time': 1700763118, 'status': 1, 'message': "'group'", 'time_elapsed': 0}]
Loading plugin: kahi_scienti_person
Running plugin: kahi_scienti_person
Processing scienti_uec_2023 database
Plugin scienti_person failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_person/Kahi_scienti_person.py", line 317, in run
    self.insert_scienti(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_person/Kahi_scienti_person.py", line 254, in insert_scienti
    {"external_ids.id": prod["group"][0]["COD_ID_GRUPO"]})
                        ~~~~^^^^^^^^^
KeyError: 'group'
```

**Comment by muzgash** [comment]
Fixed in commit [4181757](https://github.com/colav/Kahi_plugins/commit/41817572022de570ed0ea8d614c90ef65bae46ee)
