### ISSUE TITLE
parsing date error for udea

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#109]
config 
failing for scienti_udea_2023

```.py
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi_log
  log_collection: log
workflow:
  scienti_person:
    databases:
      - database_url: localhost:27017
        database_name: scienti_udea_2023
        collection_name: product
    verbose: 2

```

```.py
ozapatam@tuxito:~/data/kahi_data/kahi_data$ kahi_run --workflow configs/Kahi_scienti_person.yml --verbose 5
OrderedDict([('config', OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'kahi'), ('log_database', 'kahi_log'), ('log_collection', 'log')])), ('workflow', OrderedDict([('scienti_person', OrderedDict([('databases', [OrderedDict([('database_url', 'localhost:27017'), ('database_name', 'scienti_udea_2023'), ('collection_name', 'product')])]), ('verbose', 2)]))]))])
Log retrieved from database
[{'_id': 'scienti_affiliations', 'time': 1700763118, 'status': 1, 'message': "'group'", 'time_elapsed': 0}, {'_id': 'scienti_person', 'time': 1700766743, 'status': 1, 'message': "time data '2017-06-09 12:28:13' does not match format '%a, %d %b %Y %H:%M:%S %Z'", 'time_elapsed': 0}]
Loading plugin: kahi_scienti_person
Running plugin: kahi_scienti_person
Processing scienti_udea_2023 database
Plugin scienti_person failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_person/Kahi_scienti_person.py", line 317, in run
    self.insert_scienti(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_person/Kahi_scienti_person.py", line 294, in insert_scienti
    date = int(dt.strptime(
               ^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2017-06-09 12:28:13' does not match format '%a, %d %b %Y %H:%M:%S %Z'
```

**Comment by muzgash** [comment]
Fixed in commit [92b506e](https://github.com/colav/Kahi_plugins/commit/92b506e3684f66449cf141c302dc52081114c923)
