### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#111]
after inserting some works it fails.

```.py
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi
  log_collection: log
workflow:
  scienti_works:
    databases:
      - database_url: localhost:27017
        database_name: scienti_udea_2023
        collection_name: product
    num_jobs: 20
    verbose: 5

```

```.py
Plugin scienti_works failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 450, in run
    self.process_scienti(config)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 430, in process_scienti
    Parallel(
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 255, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 255, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 286, in process_one
    entry = parse_scienti(scienti_reg, empty_work.copy())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 156, in parse_scienti
    details = reg["details"][0]["article"][0]
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'article'
```

**Comment by muzgash** [comment]
Fixed on commit [82c0b12](https://github.com/colav/Kahi_plugins/commit/82c0b12d5ef006d1477e0d4ca450e31574f5b2d9)
