### ISSUE TITLE
TypeError NoneType

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#113]
config file

```.yml
config:
  database_url: localhost:27017
  database_name: kahi
  log_database: kahi_log
  log_collection: log
workflow:
  staff_udea_affiliations:
    file_path: udea/Base de Datos profesores 2019_con_clasificación de Colciencias.xlsx
```

error
```.py
ozapatam@tuxito:~/data/kahi_data/kahi_data$ kahi_run --workflow configs/Kahi_staff_udea_affiliations.yml 
University of Antioquia not found in database. Creating it with minimal information...
Plugin staff_udea_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_staff_udea_affiliations/Kahi_staff_udea_affiliations.py", line 146, in run
    {"id": self.udea_reg["_id"], "name": "Universidad de Antioquia", "types": self.udea_reg["types"]})
           ~~~~~~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by muzgash** [comment]
Fixed since commit [05cf8db](https://github.com/colav/Kahi_plugins/commit/05cf8dbe6cfa1c43cf0673841c0bee3b72a8ec81)
