### ISSUE TITLE
error with details 

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#185]
* this is only with product COD 111
* in the collection product_univalle

check with
```
db.product_univalle.findOne({"details":{$exists:0}})
```
```
Plugin scienti_sources failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 144, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_sources/Kahi_scienti_sources.py", line 286, in run
    self.process_scienti(config, verbose=5)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_sources/Kahi_scienti_sources.py", line 196, in process_scienti
    for detail in reg_scienti["details"]:
                  ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'details'
```

**Comment by omazapa** [comment]
done via #184
