### ISSUE TITLE
error with group

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#186]
only with products 111
config example
```
  scienti_affiliations:
    databases:
      - database_url: localhost:27017
        database_name: scienti_111_all
        collection_name: product_udea
```
```
Plugin scienti_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 144, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 280, in run
    self.process_scienti_groups(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 210, in process_scienti_groups
    group = group["group"][0]
            ~~~~~^^^^^^^^^
KeyError: 'group'
```

**Comment by omazapa** [comment]
fixed via pr #189
