### ISSUE TITLE
[Kahi_minciencias_opendata_affiliations] key error postcode

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#220]
Plugin minciencias_opendata_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 144, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_minciencias_opendata_affiliations/Kahi_minciencias_opendata_affiliations.py", line 223, in run
    self.process_openadata()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_minciencias_opendata_affiliations/Kahi_minciencias_opendata_affiliations.py", line 189, in process_openadata
    "postcode": institution["addresses"][0]["postcode"],
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'postcode'

**Comment by omazapa** [comment]
closed via #224
