### ISSUE TITLE
Plugin scienti_sources failed

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#56]
kahi_run --workflow udea.yaml 
Processing scienti_111 database
Plugin scienti_sources failed
Traceback (most recent call last):
  File "/usr/local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/usr/local/lib/python3.9/dist-packages/kahi/Kahi.py", line 126, in run
    status = run()
  File "/usr/local/lib/python3.9/dist-packages/kahi_scienti_sources/Kahi_scienti_sources.py", line 250, in run
    self.process_scienti(config, verbose=5)
  File "/usr/local/lib/python3.9/dist-packages/kahi_scienti_sources/Kahi_scienti_sources.py", line 168, in process_scienti
    if "TPO_CLASIFICACION" not in journal.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by muzgash** [comment]
Fixed in version 0.0.3a0
