### ISSUE TITLE
[scienti_affiliations]

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#61]
```
Processing scienti_111 database
Plugin scienti_affiliations failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 220, in run
    self.process_scienti_institutions(config, verbose=self.verbose)
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_affiliations/Kahi_scienti_affiliations.py", line 68, in process_scienti_institutions
    name = reg_col["names"][0]["name"]
           ~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by muzgash** [comment]
Fixed in version 0.0.3a0
