### ISSUE TITLE
[openalex_person]

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#64]
```
[Parallel(n_jobs=20)]: Done 331276 tasks      | elapsed:  4.4min
Plugin openalex_person failed
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_openalex_person/Kahi_openalex_person.py", line 16, in process_one
    author = collection.find_one({"external_ids.id": idx})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/collection.py", line 1470, in find_one
    for result in cursor.limit(-1):
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/cursor.py", line 1251, in next
    if len(self.__data) or self._refresh():
                           ^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/cursor.py", line 1142, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1758, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1703, in __start_session
    self._topology._check_implicit_session_support()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/home/ozapatam/.local/lib/python3.11/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: No servers found yet, Timeout: 30s, Topology Description: <TopologyDescription id: 64ea720979d4776dee67ff68, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_openalex_person/Kahi_openalex_person.py", line 122, in run
    self.process_openalex()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_openalex_person/Kahi_openalex_person.py", line 109, in process_openalex
    Parallel(
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
pymongo.errors.ServerSelectionTimeoutError: No servers found yet, Timeout: 30s, Topology Description: <TopologyDescription id: 64ea720979d4776dee67ff68, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None>]>
```

**Comment by muzgash** [comment]
Fixed in version 0.0.3a0
