### ISSUE TITLE
[kahi_works]

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#65]
```
Loading plugin: kahi_works
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 85, in run
    self.plugins[module_name] = import_module(
                                ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_works/Kahi_works.py", line 16, in <module>
    from lingua import LanguageDetectorBuilder
ImportError: cannot import name 'LanguageDetectorBuilder' from 'lingua' (/home/ozapatam/.local/lib/python3.11/site-packages/lingua/__init__.py)

```

**Comment by muzgash** [comment]
Deprecated.
