### ISSUE TITLE
[openalex_subjects] Must review parallelization with loky backend and mongodb cursors

### ISSUE THREAD

**Issue by muzgash** [colav/Kahi_plugins#75]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/network.py", line 181, in command
    reply = receive_message(conn, request_id)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/network.py", line 247, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "/usr/local/lib/python3.10/dist-packages/pymongo/network.py", line 336, in _receive_data_on_socket
    raise OSError("connection closed")
OSError: connection closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/muzgash/.local/lib/python3.10/site-packages/kahi_openalex_subjects/Kahi_openalex_subjects.py", line 48, in process_relation
    collection.update_one({"external_ids.id": sub["id"]}, {
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 1088, in update_one
    self._update_retryable(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 883, in _update_retryable
    return self.__database.client._retryable_write(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1568, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1413, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1460, in _retry_internal
    return func(session, conn, retryable)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 864, in _update
    return self._update(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 818, in _update
    result = conn.command(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 960, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 1134, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/pool.py", line 406, in _raise_connection_failure
    raise AutoReconnect(msg) from error
pymongo.errors.AutoReconnect: localhost:27017: connection closed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/muzgash/.local/lib/python3.10/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
  File "/home/muzgash/.local/lib/python3.10/site-packages/kahi_openalex_subjects/Kahi_openalex_subjects.py", line 166, in run
    self.process_relations()
  File "/home/muzgash/.local/lib/python3.10/site-packages/kahi_openalex_subjects/Kahi_openalex_subjects.py", line 156, in process_relations
    Parallel(
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
pymongo.errors.AutoReconnect: localhost:27017: connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/muzgash/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/muzgash/.local/lib/python3.10/site-packages/kahi/Kahi.py", line 162, in run
    ].find_one({"_id": module_name}):
  File "/usr/local/lib/python3.10/dist-packages/pymongo/collection.py", line 1508, in find_one
    for result in cursor.limit(-1):
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1262, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.10/dist-packages/pymongo/cursor.py", line 1153, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1868, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 1811, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 583, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 595, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6526fd368d5a3bbbe81a0856, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

**Comment by muzgash** [comment]
Fixed on version 0.0.3-alpha
